# Generated by Django 5.2.4 on 2025-07-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
