# Generated by Django 5.2.4 on 2025-08-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contacto_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
