# Generated by Django 5.2.4 on 2025-08-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tiposolicitud_alter_contacto_tipo_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_elavoracion',
            new_name='fecha_elaboracion',
        ),
    ]
